#! /bin/bash -eu

# FIXME(psi): wrapper.shと限りなくかぶっているが、
#             readlink_fの依存関係上これを回避する方法が思いつかない

# from: https://qiita.com/edvakf@github/items/b8400f7dfe9210aadddd
function readlink_f() {
  local TARGET_FILE=$1
  cd $(dirname ${TARGET_FILE})
  TARGET_FILE=$(basename ${TARGET_FILE})

  # Iterate down a (possible) chain of symlinks
  while [ -L "${TARGET_FILE}" ]
  do
      TARGET_FILE=$(readlink ${TARGET_FILE})
      cd $(dirname ${TARGET_FILE})
      TARGET_FILE=$(basename ${TARGET_FILE})
  done

  # Compute the canonicalized name by finding the physical path
  # for the directory we're in and appending the target file.
  local PHYS_DIR=$(pwd -P)
  echo ${PHYS_DIR}/${TARGET_FILE}
}

# zshではsourceすると$0はこのactivateのパスになるが、
# bashではそれに対応するのは${BASH_SOURCE}なのだ。
# See: https://stackoverflow.com/questions/35006457/choosing-between-0-and-bash-source
SCRIPT_PATH=${BASH_SOURCE:-$0}
SCRIPT_PATH=$(readlink_f ${SCRIPT_PATH})
SCRIPT_DIR=$(cd $(dirname ${SCRIPT_PATH}); pwd)

if [ -e "${SCRIPT_DIR}/../../req.txt" ]; then
  REQ_TXT="${SCRIPT_DIR}/../../req.txt"
else
  REQ_TXT=${SCRIPT_DIR}/req.txt
fi

REQUIREMENT_HASH=$(cat ${REQ_TXT} | openssl dgst -md5 | sed 's/^.* //')
VENV_DIR=$(cd ${SCRIPT_DIR}/../_venvs; pwd)/${REQUIREMENT_HASH}

bash ${SCRIPT_DIR}/prepare.sh ${VENV_DIR}
source ${VENV_DIR}/bin/activate

unset REQUIREMENT_HASH
unset SCRIPT_PATH
unset SCRIPT_DIR
unset VENV_DIR
unset -f readlink_f
